import { Pet } from "@/types";

export const mockPets: Pet[] = [
  {
    id: "pet-1",
    shelter_id: "shelter-1",
    name: "Luna",
    pet_type: "perro",
    sex: "hembra",
    estimated_age_months: 24,
    estimated_size: "mediano",
    breed: "Mestiza",
    color: "Negro y blanco",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: false,
    apt_for_apartment: true,
    energy_level: "medio",
    personality: "Luna es muy sociable y le encanta pasear. Es ideal para una familia.",
    story: "Fue encontrada en una plaza de Lomas de Zamora cuando tenía 3 meses.",
    adoption_requirements: "Vivienda segura, patio o paseos diarios, compromiso de salud.",
    photos: ["https://placedog.net/500/500?id=1", "https://placedog.net/500/500?id=2"],
    status: "disponible",
    views_count: 145,
    created_at: "2024-03-01T12:00:00Z",
    updated_at: "2024-03-10T14:30:00Z",
  },
  {
    id: "pet-2",
    shelter_id: "shelter-1",
    name: "Simón",
    pet_type: "perro",
    sex: "macho",
    estimated_age_months: 6,
    estimated_size: "chico",
    breed: "Mestizo",
    color: "Marrón claro",
    is_neutered: false,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: true,
    energy_level: "alto",
    personality: "Cachorro super juguetón y mimoso. Está en etapa de aprendizaje.",
    story: "Nació en el refugio después de que rescatamos a su mamá.",
    adoption_requirements: "Paciencia para educar un cachorro, tiempo para juegos.",
    photos: ["https://placedog.net/500/500?id=3"],
    status: "disponible",
    views_count: 320,
    created_at: "2024-03-15T10:00:00Z",
    updated_at: "2024-03-15T10:00:00Z",
  },
  {
    id: "pet-3",
    shelter_id: "shelter-2",
    name: "Pelusa",
    pet_type: "gato",
    sex: "hembra",
    estimated_age_months: 12,
    estimated_size: "chico",
    breed: "Común Europeo",
    color: "Gris atigrado",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: false,
    good_with_cats: true,
    apt_for_apartment: true,
    energy_level: "bajo",
    personality: "Tranquila, le gusta dormir al sol. Es un poco tímida al principio.",
    story: "Rescatada de un techo en Tigre.",
    adoption_requirements: "Red de protección en ventanas es excluyente.",
    photos: ["https://placekitten.com/500/501"],
    status: "disponible",
    views_count: 89,
    created_at: "2024-02-20T11:00:00Z",
    updated_at: "2024-03-01T09:00:00Z",
  },
  {
    id: "pet-4",
    shelter_id: "shelter-4",
    name: "Toto",
    pet_type: "perro",
    sex: "macho",
    estimated_age_months: 120,
    estimated_size: "grande",
    breed: "Labrador mestizo",
    color: "Dorado",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: false,
    energy_level: "bajo",
    personality: "Un abuelo bonachón que solo busca cariño y una cama calentita.",
    story: "Vivió toda su vida en la calle cerca de una fábrica hasta que cerró.",
    adoption_requirements: "Casa con patio, mucho amor para sus últimos años.",
    photos: ["https://placedog.net/500/500?id=4"],
    status: "disponible",
    views_count: 210,
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-01-10T08:00:00Z",
  },
  {
    id: "pet-5",
    shelter_id: "shelter-3",
    name: "Coco",
    pet_type: "gato",
    sex: "macho",
    estimated_age_months: 3,
    estimated_size: "chico",
    color: "Naranja",
    is_neutered: false,
    vaccines_up_to_date: false,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: true,
    energy_level: "alto",
    personality: "Inquieto, explorador y muy ronroneador.",
    story: "Lo tiraron en una caja en una veterinaria.",
    adoption_requirements: "Seguridad total en el hogar, compromiso de castración.",
    photos: ["https://placekitten.com/500/502"],
    status: "en_proceso",
    views_count: 450,
    created_at: "2024-03-20T16:00:00Z",
    updated_at: "2024-03-22T12:00:00Z",
  },
  {
    id: "pet-6",
    shelter_id: "shelter-1",
    name: "Maru",
    pet_type: "perro",
    sex: "hembra",
    estimated_age_months: 36,
    estimated_size: "grande",
    color: "Blanco con manchas marrones",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: false,
    good_with_dogs: true,
    good_with_cats: false,
    apt_for_apartment: false,
    energy_level: "alto",
    personality: "Guardiana, leal y muy inteligente. Necesita espacio para correr.",
    story: "Abandonada en la ruta, rescatada por un camionero.",
    adoption_requirements: "Dueño con experiencia en perros grandes, espacio amplio.",
    photos: ["https://placedog.net/500/500?id=5"],
    status: "disponible",
    views_count: 56,
    created_at: "2024-02-15T09:00:00Z",
    updated_at: "2024-02-15T09:00:00Z",
  },
  {
    id: "pet-7",
    shelter_id: "shelter-2",
    name: "Rocco",
    pet_type: "perro",
    sex: "macho",
    estimated_age_months: 18,
    estimated_size: "mediano",
    breed: "Pitbull mestizo",
    color: "Gris",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: false,
    good_with_dogs: false,
    good_with_cats: false,
    apt_for_apartment: true,
    energy_level: "alto",
    personality: "Es un dulce con las personas pero no se lleva bien con otros animales.",
    story: "Rescatado de una pelea de perros.",
    adoption_requirements: "Hogar sin otras mascotas, paseos obligatorios con bozal.",
    photos: ["https://placedog.net/500/500?id=6"],
    status: "disponible",
    views_count: 112,
    created_at: "2024-03-05T14:00:00Z",
    updated_at: "2024-03-05T14:00:00Z",
  },
  {
    id: "pet-8",
    shelter_id: "shelter-3",
    name: "Mochi",
    pet_type: "gato",
    sex: "hembra",
    estimated_age_months: 5,
    estimated_size: "chico",
    color: "Calicó",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: true,
    energy_level: "medio",
    personality: "Muy independiente pero charlatana. Le encanta que le hablen.",
    story: "Nació en un jardín balbuceando hasta que la rescatamos.",
    adoption_requirements: "Red de protección, mucho juego.",
    photos: ["https://placekitten.com/500/503"],
    status: "disponible",
    views_count: 178,
    created_at: "2024-03-10T11:00:00Z",
    updated_at: "2024-03-10T11:00:00Z",
  },
  {
    id: "pet-9",
    shelter_id: "shelter-4",
    name: "Oso",
    pet_type: "perro",
    sex: "macho",
    estimated_age_months: 48,
    estimated_size: "grande",
    color: "Negro",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: false,
    energy_level: "medio",
    personality: "Es una manta con patas. Solo quiere amor.",
    story: "Vivía en una gomería donde lo querían mucho pero no podían tenerlo más.",
    adoption_requirements: "Espacio intermedio, compromiso de salud.",
    photos: ["https://placedog.net/500/500?id=7"],
    status: "adoptada",
    views_count: 540,
    created_at: "2023-12-01T10:00:00Z",
    updated_at: "2024-02-15T15:00:00Z",
    adopted_at: "2024-02-15T15:00:00Z",
  },
  {
    id: "pet-10",
    shelter_id: "shelter-1",
    name: "Frida",
    pet_type: "gato",
    sex: "hembra",
    estimated_age_months: 24,
    estimated_size: "chico",
    color: "Carey",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: false,
    apt_for_apartment: true,
    energy_level: "bajo",
    personality: "Reina absoluta del sillón. No le gustan los otros gatos.",
    story: "Su anterior dueño falleció y la familia no podía tenerla.",
    adoption_requirements: "Lugar tranquilo, sin ruidos fuertes.",
    photos: ["https://placekitten.com/500/504"],
    status: "disponible",
    views_count: 65,
    created_at: "2024-03-25T13:00:00Z",
    updated_at: "2024-03-25T13:00:00Z",
  },
  {
    id: "pet-11",
    shelter_id: "shelter-5",
    name: "Pichu",
    pet_type: "perro",
    sex: "macho",
    estimated_age_months: 2,
    estimated_size: "chico",
    color: "Blanco con canela",
    is_neutered: false,
    vaccines_up_to_date: false,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: true,
    energy_level: "alto",
    personality: "Chiquito pero con mucha personalidad. Llora si lo dejan solo.",
    story: "Abandonado en una plaza en Lanús Este.",
    adoption_requirements: "Paciente para enseñarle, disponibilidad horaria.",
    photos: ["https://placedog.net/500/500?id=8"],
    status: "disponible",
    views_count: 890,
    created_at: "2024-04-01T10:00:00Z",
    updated_at: "2024-04-01T10:00:00Z",
  },
  {
    id: "pet-12",
    shelter_id: "shelter-1",
    name: "Duke",
    pet_type: "perro",
    sex: "macho",
    estimated_age_months: 60,
    estimated_size: "grande",
    breed: "Ovejero mestizo",
    color: "Negro y fuego",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: false,
    apt_for_apartment: false,
    energy_level: "bajo",
    personality: "Tranquilo, obediente y muy educado.",
    story: "Rescatado de una situación de maltrato en el sur del conurbano.",
    adoption_requirements: "Casa con patio bien cerrado.",
    photos: ["https://placedog.net/500/500?id=9"],
    status: "disponible",
    views_count: 42,
    created_at: "2024-02-10T12:00:00Z",
    updated_at: "2024-02-10T12:00:00Z",
  },
  {
    id: "pet-13",
    shelter_id: "shelter-2",
    name: "Milo",
    pet_type: "gato",
    sex: "macho",
    estimated_age_months: 8,
    estimated_size: "chico",
    color: "Negro",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: true,
    energy_level: "medio",
    personality: "Suertudo y mimoso. Le gusta dormir en los hombros.",
    story: "Apareció en un motor de auto en invierno.",
    adoption_requirements: "Seguridad para gatos en el hogar.",
    photos: ["https://placekitten.com/500/505"],
    status: "disponible",
    views_count: 245,
    created_at: "2024-03-15T09:45:00Z",
    updated_at: "2024-03-15T09:45:00Z",
  },
  {
    id: "pet-14",
    shelter_id: "shelter-3",
    name: "Cloe",
    pet_type: "gato",
    sex: "hembra",
    estimated_age_months: 18,
    estimated_size: "chico",
    color: "Blanca",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: true,
    energy_level: "bajo",
    personality: "Rescatada y muy agradecida. Solo quiere estar cerquita.",
    story: "La rescatamos de una demolición en Morón.",
    adoption_requirements: "Hogar amoroso y red de protección.",
    photos: ["https://placekitten.com/500/506"],
    status: "disponible",
    views_count: 130,
    created_at: "2024-03-28T11:00:00Z",
    updated_at: "2024-03-28T11:00:00Z",
  },
  {
    id: "pet-15",
    shelter_id: "shelter-4",
    name: "Tita",
    pet_type: "perro",
    sex: "hembra",
    estimated_age_months: 72,
    estimated_size: "chico",
    breed: "Mestiza salchicha",
    color: "Marrón chocolate",
    is_neutered: true,
    vaccines_up_to_date: true,
    is_dewormed: true,
    good_with_children: true,
    good_with_dogs: true,
    good_with_cats: true,
    apt_for_apartment: true,
    energy_level: "bajo",
    personality: "Pequeña gruñona de buen corazón. Ladra para pedir comida.",
    story: "La encontramos en Constitución, estaba muy flaquita.",
    adoption_requirements: "Lugar con pocos escalones por su columna.",
    photos: ["https://placedog.net/500/500?id=10"],
    status: "disponible",
    views_count: 98,
    created_at: "2024-03-30T10:00:00Z",
    updated_at: "2024-03-30T10:00:00Z",
  }
];
