import { AdoptionApplication } from "@/types";

export const mockApplications: AdoptionApplication[] = [
  {
    id: "app-1",
    pet_id: "pet-1",
    adopter_id: "user-1",
    shelter_id: "shelter-1",
    status: "pendiente",
    reason_to_adopt: "Me encanta Luna, tengo una perra y me gustaría que tenga compañía. Tenemos mucho parque.",
    daily_hours_alone: 4,
    can_afford_vet: true,
    vet_explanation: "Tengo mi veterinario de confianza a 2 cuadras.",
    commitment_signed: true,
    created_at: "2024-03-25T10:00:00Z",
    updated_at: "2024-03-25T10:00:00Z",
  },
  {
    id: "app-2",
    pet_id: "pet-2",
    adopter_id: "user-2",
    shelter_id: "shelter-1",
    status: "en_revision",
    reason_to_adopt: "Buscamos un cachorro para mis hijos. Tenemos patio grande y cercado.",
    daily_hours_alone: 2,
    can_afford_vet: true,
    vet_explanation: "Estamos dispuestos a cubrir todos los gastos necesarios.",
    commitment_signed: true,
    created_at: "2024-03-26T14:30:00Z",
    updated_at: "2024-03-27T09:00:00Z",
  },
  {
    id: "app-3",
    pet_id: "pet-10",
    adopter_id: "user-3",
    shelter_id: "shelter-1",
    status: "rechazada",
    reason_to_adopt: "Quiero una gatita tranquila.",
    daily_hours_alone: 10,
    can_afford_vet: true,
    vet_explanation: "Si.",
    commitment_signed: true,
    rejection_reason: "Muchas horas sola y falta de red en el departamento.",
    created_at: "2024-03-28T16:00:00Z",
    updated_at: "2024-03-29T11:00:00Z",
  },
  {
    id: "app-4",
    pet_id: "pet-3",
    adopter_id: "user-1",
    shelter_id: "shelter-2",
    status: "aceptada",
    reason_to_adopt: "Quiero adoptar a Pelusa para que viva en casa con mi otra gatita.",
    daily_hours_alone: 3,
    can_afford_vet: true,
    vet_explanation: "Trabajo remoto así que estoy siempre.",
    commitment_signed: true,
    created_at: "2024-03-20T10:00:00Z",
    updated_at: "2024-03-24T15:00:00Z",
  },
  {
    id: "app-5",
    pet_id: "pet-9",
    adopter_id: "user-2",
    shelter_id: "shelter-4",
    status: "concretada",
    reason_to_adopt: "Oso es hermoso, queremos darle un buen hogar en sus últimos años.",
    daily_hours_alone: 0,
    can_afford_vet: true,
    vet_explanation: "Somos jubilados y estamos siempre en casa.",
    commitment_signed: true,
    created_at: "2024-01-15T09:00:00Z",
    updated_at: "2024-02-15T15:00:00Z",
  }
];
