import { Vendor } from "@/types";

export const mockVendors: Vendor[] = [
  {
    profile_id: "vendor-1",
    business_name: "Pet Shop El Ovejero",
    business_type: "petshop",
    cuit: "20-98765432-1",
    description: "Venta de alimento balanceado, accesorios y farmacia veterinaria en zona sur.",
    categories: ["alimento", "accesorios", "farmacia"],
    address: "Av. Hipólito Yrigoyen 4500, Lanús",
    whatsapp: "+5491112345678",
    verification_status: "approved",
    plan: "premium",
    commission_rate: 10,
  },
  {
    profile_id: "vendor-2",
    business_name: "Mundo Canino Belgrano",
    business_type: "petshop",
    cuit: "30-11223344-5",
    description: "Lo mejor para tu perro en Capital Federal. Trabajamos con marcas importadas.",
    categories: ["alimento", "juguetes", "higiene"],
    address: "Av. Cabildo 2100, CABA",
    verification_status: "approved",
    plan: "pro",
    commission_rate: 12,
  },
  {
    profile_id: "vendor-3",
    business_name: "Gatomanía",
    business_type: "emprendedor",
    cuit: "27-33445566-7",
    description: "Hacemos rascadores artesanales y juguetes especiales para gatos.",
    categories: ["juguetes", "muebles"],
    address: "Caseros, Tres de Febrero",
    verification_status: "approved",
    plan: "basic",
    commission_rate: 5,
  },
  {
    profile_id: "vendor-4",
    business_name: "Veterinaria San Roque",
    business_type: "veterinaria",
    cuit: "30-55667788-9",
    description: "Clínica 24hs y tienda de especialidades veterinarias.",
    categories: ["farmacia", "alimento_medicado"],
    address: "Ramos Mejía, La Matanza",
    verification_status: "approved",
    plan: "premium",
    commission_rate: 8,
  },
  {
    profile_id: "vendor-5",
    business_name: "Paseo Animal",
    business_type: "marca",
    cuit: "30-99887766-5",
    description: "Marca argentina de accesorios premium para mascotas.",
    categories: ["accesorios", "ropa"],
    address: "Palermo, CABA",
    verification_status: "approved",
    plan: "pro",
    commission_rate: 15,
  },
  {
    profile_id: "vendor-6",
    business_name: "Nutriland",
    business_type: "emprendedor",
    cuit: "20-11112222-3",
    description: "Alimento natural y snacks deshidratados sin conservantes.",
    categories: ["alimento", "snacks"],
    address: "Quilmes, GBA Sur",
    verification_status: "pending",
    plan: "basic",
    commission_rate: 5,
  },
  {
    profile_id: "vendor-7",
    business_name: "Zarpazos",
    business_type: "petshop",
    cuit: "30-44445555-6",
    description: "Pet shop con envío gratis en todo zona norte.",
    categories: ["alimento", "limpieza"],
    address: "Olivos, Vicente López",
    verification_status: "approved",
    plan: "premium",
    commission_rate: 10,
  },
  {
    profile_id: "vendor-8",
    business_name: "Hoguer de Perros",
    business_type: "emprendedor",
    cuit: "27-77778888-9",
    description: "Cuchas térmicas y camitas lavables hechas en Argentina.",
    categories: ["descanso", "camas"],
    address: "San Martín, GBA",
    verification_status: "approved",
    plan: "basic",
    commission_rate: 5,
  }
];
